version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
  api:
    build: ./api/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
      - bundle:/bundle

volumes:
  bundle:
